from __future__ import annotations

from pathlib import Path

from .state_types import ScreenState


def build_default_states(project_root: Path) -> list[ScreenState]:
    images_dir = project_root / "images" / "dratini"
    return [
        ScreenState(
            name="flying_star",
            screenshot_path=images_dir / "flying_stars.png",
            action_name="press_a",
            match_x=200,
            match_y=225,
            match_text="Matched the blue background of the flying stars intro.",
            required_runtime_state="s0",
            next_runtime_state="s0",
        ),
        ScreenState(
            name="start_screen",
            screenshot_path=images_dir / "start_screen.png",
            action_name="press_a",
            match_x=180,
            match_y=950,
            match_text="Matched start screen",
            required_runtime_state="s0",
            next_runtime_state="s0",
        ),
        ScreenState(
            name="save_screen",
            screenshot_path=images_dir / "save_screen.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Matched save screen",
            required_runtime_state="s0",
            next_runtime_state="s0",
        ),
        ScreenState(
            name="diary_skip",
            screenshot_path=images_dir / "diary_skip.png",
            action_name="press_b",
            match_x=0,
            match_y=0,
            match_text="Matched diary screen and perform skip",
            required_runtime_state="s0",
            next_runtime_state="s1",
        ),
        # first dratini
        ScreenState(
            name="start_cashier_dialog_1",
            screenshot_path=images_dir / "start_cashier_dialog.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Start first cashier dialog",
            required_runtime_state="s1",
            next_runtime_state="s1",
        ),
        ScreenState(
            name="exchange_coins_for_prizes_1",
            screenshot_path=images_dir / "exchange_coins_for_prizes.png",
            action_name="press_a",
            match_x=250,
            match_y=800,
            match_text="We exchange coins for prizes dialog",
            required_runtime_state="s1",
            next_runtime_state="s1",
        ),
        ScreenState(
            name="buy_dratini_sequence_1",
            screenshot_path=images_dir / "buy_dratini.png",
            action_name="buy_dratini_sequence", # joystick down, joystick down, button a
            match_x=0,
            match_y=0,
            match_text="Start first dratini buying sequence",
            required_runtime_state="s1",
            next_runtime_state="s1",
        ),
        ScreenState(
            name="confirm_dratini_1",
            screenshot_path=images_dir / "buy_dratini_confirmation.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Start first dratini buying confirmation",
            required_runtime_state="s1",
            next_runtime_state="s1",
        ),
        ScreenState(
            name="skip_nickname_1",
            screenshot_path=images_dir / "skip_nickname.png",
            action_name="press_b",
            match_x=0,
            match_y=0,
            match_text="Start second dratini nickname skip",
            required_runtime_state="s1",
            next_runtime_state="s2",
        ),
        # second dratini
        ScreenState(
            name="start_cashier_dialog_2",
            screenshot_path=images_dir / "start_cashier_dialog.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Start second cashier dialog",
            required_runtime_state="s2",
            next_runtime_state="s2",
        ),
        ScreenState(
            name="exchange_coins_for_prizes_2",
            screenshot_path=images_dir / "exchange_coins_for_prizes.png",
            action_name="press_a",
            match_x=250,
            match_y=800,
            match_text="We exchange coins for prizes dialog",
            required_runtime_state="s2",
            next_runtime_state="s2",
        ),
        ScreenState(
            name="buy_dratini_sequence_2",
            screenshot_path=images_dir / "buy_dratini.png",
            action_name="buy_dratini_sequence", # joystick down, joystick down, button a
            match_x=0,
            match_y=0,
            match_text="Start second dratini buying sequence",
            required_runtime_state="s2",
            next_runtime_state="s2",
        ),
        ScreenState(
            name="confirm_dratini_2",
            screenshot_path=images_dir / "buy_dratini_confirmation.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Start second dratini buying confirmation",
            required_runtime_state="s2",
            next_runtime_state="s2",
        ),
        ScreenState(
            name="skip_nickname_2",
            screenshot_path=images_dir / "skip_nickname.png",
            action_name="press_b",
            match_x=0,
            match_y=0,
            match_text="Start second dratini nickname skip",
            required_runtime_state="s2",
            next_runtime_state="s3",
        ),
        # third dratini
        ScreenState(
            name="start_cashier_dialog_3",
            screenshot_path=images_dir / "start_cashier_dialog.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Start third cashier dialog",
            required_runtime_state="s3",
            next_runtime_state="s3",
        ),
        ScreenState(
            name="exchange_coins_for_prizes_3",
            screenshot_path=images_dir / "exchange_coins_for_prizes.png",
            action_name="press_a",
            match_x=250,
            match_y=800,
            match_text="We exchange coins for prizes dialog",
            required_runtime_state="s3",
            next_runtime_state="s3",
        ),
        ScreenState(
            name="buy_dratini_sequence_3",
            screenshot_path=images_dir / "buy_dratini.png",
            action_name="buy_dratini_sequence",
            match_x=0,
            match_y=0,
            match_text="Start third dratini buying sequence",
            required_runtime_state="s3",
            next_runtime_state="s3",
        ),
        ScreenState(
            name="confirm_dratini_3",
            screenshot_path=images_dir / "buy_dratini_confirmation.png",
            action_name="press_a",
            match_x=0,
            match_y=0,
            match_text="Start first dratini buying confirmation",
            required_runtime_state="s3",
            next_runtime_state="s3",
        ),
        ScreenState(
            name="skip_nickname_3",
            screenshot_path=images_dir / "skip_nickname.png",
            action_name="press_b",
            match_x=0,
            match_y=0,
            match_text="Start third dratini nickname skip",
            required_runtime_state="s3",
            next_runtime_state="s4",
        ),
        # check all three
        ScreenState(
            name="open_menu",
            screenshot_path=images_dir / "open_status.png",
            action_name="open_first_pokemon_status_sequence",
            match_x=0,
            match_y=0,
            match_text="Open menu",
            required_runtime_state="s4",
            next_runtime_state="s4",
        ),
        ScreenState(
            name="if_first_no_shiny_go_to_second",
            screenshot_path=images_dir / "check_if_non_shiny.png",
            action_name="press_down",
            match_x=0,
            match_y=0,
            match_text="Check if dratini pokemon is shiny -> no",
            required_runtime_state="s4",
            next_runtime_state="s5",
        ),
        ScreenState(
            name="if_second_no_shiny_go_to_third",
            screenshot_path=images_dir / "check_if_non_shiny.png",
            action_name="press_down",
            match_x=0,
            match_y=0,
            match_text="Check if dratini pokemon is shiny -> no",
            required_runtime_state="s5",
            next_runtime_state="s6",
        ),
        ScreenState(
            name="if_third_no_shiny_reset",
            screenshot_path=images_dir / "check_if_non_shiny.png",
            action_name="press_abxy",
            match_x=0,
            match_y=0,
            match_text="Check if dratini pokemon is shiny -> no",
            required_runtime_state="s6",
            next_runtime_state="s0",
        ),
  ]
